const { Client } = require('pg');

const clearSQL = `
DROP TABLE IF EXISTS users, posts, comments, session CASCADE;
`;

const populateSQL = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  first VARCHAR(50),
  last VARCHAR(50),
  username VARCHAR(50) UNIQUE,
  password VARCHAR(100),
  admin BOOLEAN DEFAULT FALSE,
  has_pic BOOLEAN DEFAULT FALSE,
  pic_version VARCHAR(50),
  bio VARCHAR(250),
  loc VARCHAR(50),
  birthday DATE,
  added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(250),
  message TEXT,
  added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  message VARCHAR(2000),
  added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (first, last, username, password, admin, has_pic, pic_version, bio, loc, birthday)
VALUES
  ('Jace', 'Mitchell', 'jace_mitch', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Trying to turn caffeine into code.', 'Austin', '2002-06-15'),
  ('Jason', 'Smith', 'jsmithy', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'Professional overthinker. Amateur pizza critic.', 'Denver', '1998-11-02'),
  ('Jace', 'Taylor', 'jtaytay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, '', '', NULL),
  ('Jace', 'Bennett', 'jace_bennett', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'My hobbies include breathing and regretting my Netflix choices.', 'Nashville', '1995-01-09'),
  ('Jacelyn', 'Brooks', 'jacelynb', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Professional third-wheeler.', 'Seattle', '1993-03-19'),
  ('Jace', 'Daniels', 'jdaniels', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'Probably camping right now. Or thinking about it.', 'Boise', '1997-09-30'),
  ('Jason', 'Evans', 'jayevans34', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Recovering perfectionist. Current disaster.', 'San Francisco', '2000-05-21'),
  ('Jace', 'Fisher', 'fisherman_jace', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'I peaked in Mario Kart.', '', NULL),
  ('Jason', 'Greene', 'greene_jason', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Loudly quiet since 1990.', 'Chicago', '1990-12-14'),
  ('Jace', 'Howard', 'howardj', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'This is my location bio. Groundbreaking, I know.', 'New York', '2001-02-22'),
  ('Jason', 'Irwin', 'jirwin77', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Currently accepting bad advice.', '', NULL),
  ('Jace', 'Jackson', 'jacejackson', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Hot take: pineapple belongs on pizza.', 'Phoenix', '1996-07-11'),
  ('Jason', 'Kelly', 'kellyjay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'The human equivalent of a shrug emoji.', 'Boston', '1989-01-05'),
  ('Jace', 'Lopez', 'lopezjace', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Sarcasm is my love language.', 'Dallas', '1993-04-17'),
  ('Jacelyn', 'Moore', 'jacelynm', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, '', 'Portland', NULL),
  ('Jace', 'Nelson', 'nelsonj', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Not a morning person. Not a night person. Basically just tired.', 'Los Angeles', '2002-10-09'),
  ('Jason', 'Owens', 'owensjay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'Says "brb" and disappears for 3 days.', '', NULL),
  ('Jace', 'Peterson', 'jpeterson', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Professional nap enthusiast.', 'Columbus', '1997-05-28'),
  ('Jason', 'Quinn', 'quinnjay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'Collecting unfinished projects since 2005.', 'Atlanta', '1994-08-30'),
  ('Jace', 'Reed', 'reedjace', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'I once microwaved a Pop-Tart and lived to tell the tale.', 'Miami', NULL),
  ('Jace', 'Stevens', 'stevens_j', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', true, false, NULL, 'I own 47 tabs in my browser and 0 life skills.', '', '2000-03-13'),
  ('Jason', 'Turner', 'turnerjay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Currently pretending to work.', 'Remote', '1991-06-06'),
  ('Jace', 'Vaughn', 'vaughnj', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, '', '', NULL),
  ('Jason', 'White', 'whitejay', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Currently starring in my own sitcom, only I''m the audience.', 'Detroit', '1988-02-27'),
  ('Jace', 'Young', 'youngjace', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Don''t follow me, I''m lost too.', '', NULL),
  ('Jace', 'Zimmerman', 'zimmermanj', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Still figuring out this whole ''adult'' thing.', 'Salt Lake City', '1999-07-21'),
  ('Jason', 'Adams', 'jadams', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'This bio intentionally left blank.', 'Philadelphia', '1996-01-14'),
  ('Jacelyn', 'Brooks', 'jacelynrocks', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Professional karaoke champion in my car.', 'Las Vegas', NULL),
  ('Jace', 'Coleman', 'colemanj', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', false, false, NULL, 'Here for a good time, not a long time.', 'San Diego', '1992-11-25');

INSERT INTO posts (title, message, user_id)
VALUES
  ('My sourdough starter is named Jace Dough and it''s demanding rights', 'Day 9 of baking. Jace Dough has bubbles, attitude, and a better social life than me. If I feed it at 10 pm it''s happy; if I feed it at 10:05 pm it sulks like a drama croissant. Send help. Also, do I have to talk to it? Because I''m already doing that and I''m worried it''s listening.', 1),
  ('Denver pizza quest: send me your absolutely chaotic pies', 'Jace here. Pepperoni? Fine. Jalapeño + honey? Better. Pickles + ranch? Judge me and then join me. I want the weird stuff. Bonus points if the place looks like it hasn''t updated the menu since ''98 and the oven has a proper name like ''Bertha''.', 2),
  ('Minimalist post', ':)', 3),
  ('Confession: I have 47 tabs open and not one is the thing I should be doing', 'If procrastination were cardio I''d be a triathlete. Today''s workout: sprinting between vibes, hydrating with iced coffee, and lifting expectations nowhere near reality.', 21),
  ('Pineapple on pizza discourse, but make it Jace', 'Hot take from Phoenix Jace: pineapple belongs on pizza IF (and only if) you also add jalapeños and a chaotic drizzle of spicy honey. It''s like a flavor roller coaster that apologizes mid-ride.', 12),
  ('Camping hack from a Jace who forgets the lighter every time', 'Boise Jace here. If you forget your lighter, you can start a fire using the primal heat of embarrassment when your friends watch you fail to open a can with a knife for 12 minutes. Alternatively: bring a lighter like a regular person.', 6),
  ('''Monday again'' is my brand now', 'I posted ''Ugh. Monday.'' last month. Consider this the sequel: ''Ugh. Monday 2: Electric Boogaloo''. Plot twist: I bought the good coffee and still yawned through my soul.', 8),
  ('Karaoke update from the car', 'I absolutely crushed ''Since U Been Gone'' at a red light today. Audience: one pigeon. Feedback: he nodded. Career: skyrocketing.', 28),
  ('Fish tried to steal my sandwich (again)', 'Austin Jace reporting: sat by the river, unwrapped a sandwich, fish made eye contact like it owed me rent, then splashed my soul. Can''t prove it but I think he''s the same guy from last week.', 1),
  ('Name is Jace. Barista wrote ''Juice''. Not even mad tbh', 'Honestly? Juice is a vibe. Might legally change it for the rewards points.', 13),
  ('Help me name my new houseplant', 'She''s dramatic, bendy, and flops if ignored for 3 seconds. Thinking ''Jace-amine'' or ''Photosyntha Jace''. Other options welcome, but remember I''m sensitive.', 5),
  ('I tried ''just one episode'' and it''s Tuesday now', 'Nashville Jace with a cautionary tale: never trust autoplay. I blinked and Netflix asked if I''m still watching. Yes Netflix. I''m still here. I live here now.', 4),
  ('Accidentally invented a new productivity system called ''Panic Focus''', 'It''s where you do nothing all day and then at 9:48 pm become a Victorian chimney sweep who can also organize a spreadsheet. Patented pending.', 7),
  ('Remote work bingo (Portland edition)', '''You''re on mute.'' Dog cameo. Plant shelf flex. Sudden motorcycle parade outside. Neighbor drills something at 10:07 am daily. Bonus square: coffee shop that sells $7 muffins named ''Ethereal Crumble''.', 12),
  ('''It''s a walk'' he said. It was a hike. With switchbacks.', 'Seattle Jace trusted a friend who said ''casual walk''. Three miles later I''m bargaining with a crow about my cardio.', 5),
  ('What''s the polite way to ask upstairs Jace to stop practicing tap at 1 am', 'Love that you''re pursuing art, Jace. Hate that my ceiling is auditioning for ''Riverdance''. Advice welcomed. Legal or chaotic.', 5),
  ('I bought a GPS and it thinks I live in a lake now', 'Chicago Jace here. I turned left and it said ''begin swimming''. I cannot, Mr. Garmin. I cannot.', 9),
  ('Ketchup on eggs: chaotic neutral or chaotic evil?', 'Survey time. Stakes are high. Friendships may end. I''m team hot sauce but I will not judge you (publicly).', 10),
  ('Cooking fail so big the smoke detector filed a complaint', 'Made ''simple'' roasted potatoes. Somehow steamed them, then burned them, then created a new mineral. They tasted like crunchy sadness. Tips welcome. Kindness appreciated.', 3),
  ('''New password must include a hieroglyph'' - websites probably', 'Why is every password rule like ''8–32 chars, uppercase, lowercase, number, symbol, the original Latin of the Iliad, and a small prayer''? Asking for my thumbs.', 1),
  ('I am not a morning person. I am a noon person at best.', 'LA Jace update: tried sunrise yoga. Fell asleep in child''s pose. Teacher said that was valid. I feel seen and horizontal.', 16),
  ('Bike commuted for the first time and my legs wrote a will', 'San Diego Jace here. Great for the planet. Terrible for my quads. Someone please fetch me a smoothie and a trophy.', 29),
  ('Public service announcement: iced coffee is not a meal', 'I hear you. I respect you. I reject you. It is absolutely a meal if I believe hard enough.', 7),
  ('Vinyl mountain update: I found a jazz record that sounds like butter', 'Going through my uncle''s vinyl (2,000+!). Found a Blue Note pressing that turned my living room into a smoky lounge. I don''t even own a fedora and yet I feel obligated to nod thoughtfully.', 11),
  ('Hiking boots acquired. Confidence at 110%. Ankles at 4%.', 'Boise Jace again. Trails: 10/10. Me: 7/10. Gravity: undefeated.', 6),
  ('Crow asked me for my snacks. I complied.', 'Portland crow strolled up like we had plans. He cawed. I panicked. We''re best friends now. I think he''s named Jace too.', 12),
  ('''Do not microwave Pop-Tarts'' – I will not be silenced', 'Miami Jace here to confirm that microwaving a Pop-Tart is a heroic act. It''s warm. It''s rebellious. It''s not crispy and I do not care.', 20),
  ('Job hunting feels like shouting into a void wearing a tie', 'Applied to 37 roles this week. I''ve learned to love the phrase ''we''ll be in touch'' in the way you love a toothache.', 5),
  ('UI test: title intentionally empty', 'Just kidding.', 2),
  ('UI test: message intentionally empty', 'You fell for that again?', 22),
  ('Can a plant be petty? Because mine turned yellow out of spite', 'I watered. I rotated. I complimented. She said ''no thanks'' and dropped three leaves like a Victorian faint.', 15),
  ('Laundry mountain defeated (but at what cost)', 'Folded everything immediately like a responsible Jace and now I cannot find anything because it''s not in the pile where it lives.', 16),
  ('Staring contest with my to-do list. It won.', 'The list has crossed over from helpful into performance art. It is now a short story titled ''He Tried''.', 10),
  ('My name is Jace and I''m collecting mugs as if I''m hosting a convention', 'Why do I own 18 mugs? I live alone. If every Jace I know visited at once (and honestly they might) we''d be set.', 24),
  ('Remote day ruined by leaf blower boss fight', 'Every time I unmute to say something smart: BRAAAAAAAAAAAP. I yield. You win, Sir Leavesalot.', 7),
  ('If your pizza place sells a ''Grandma pie'' I trust you with my life', 'Denver Jace checking in: crispy corners, sauce islands, garlic confetti. If you know a place, drop it. My soul needs square pies.', 2),
  ('Does anyone else talk to their code like it can hear them', 'Austin dev Jace here. Today I whispered ''please'' to a function and it worked, which means I''m a wizard now and require a cape.', 1),
  ('Zero-thought dinner: chips with a side of chips', 'Dieticians do not interact. I will balance this with a grape later. Singular.', 4),
  ('Parking in Boston taught me humility and parallel lines', 'Found a spot so tight I had to exit the car like a snake leaving its skin. Victory nonetheless.', 13),
  ('I named my plants after the Spice Girls and now Posh is judging me', 'She sits there, glossy and silent, radiating wealth and disapproval. I love her so much.', 15),
  ('The algorithm and I are no longer on speaking terms', 'Posted a banger. Got 12 views. Meanwhile a raccoon spinning on a Roomba got 2 million. I respect the raccoon. I resent the math.', 9),
  ('Accidentally wore two different shoes to work', 'Remote work lulled me into a false sense of safety. Today was an office day. No one noticed until I proudly announced it. Classic Jace.', 22),
  ('I will never financially recover from this farmer''s market', 'Went for ''a tomato''. Left with $38 worth of vibes, a candle named ''Forest Whisper'', and bread that changed my life.', 28),
  ('Phoenix heat update: I am now a lizard', 'Stepped outside and my shadow said ''I''m out''. Pineapple pizza survived though, which proves science.', 12),
  ('Note to self: don''t grocery shop hungry', 'Came home with olives, four cheeses, a single carrot, and shampoo. Dinner is confusing but luxurious.', 18),
  ('Trying to meditate but my brain keeps narrating', 'Breath in. Breath out. Think about that thing you said in 2013. No. Return to breath. Also what''s for dinner. No. Breath. Brain please.', 3),
  ('Miami thunderstorm hit and my Wi-Fi achieved enlightenment', 'It became one with the void. I touched grass. It was damp. 7/10 experience.', 20),
  ('New rule: if a recipe says ''meanwhile, toast the spices'' I am ordering takeout', 'I respect the craft. I fear the smoke detector. We must all know our limits.', 29),
  ('Austin bats did a flyover. Felt honored like a tiny mayor', '10/10 would cheer again. They own the night. I pay bat taxes now.', 1),
  ('I asked for a regular trim and my barber gave me ''software engineer in a montage''', 'Do I look productive? Yes. Am I still procrastinating? Also yes.', 1),
  ('That moment when your coworker says ''quick question'' and it''s a 48-slide deck', 'I brought snacks. We might be here a while.', 7),
  ('Dallas taco crawl was spiritual', 'Three tacos in and I saw the face of guacamole. He told me to hydrate and I ignored him.', 14),
  ('I tried journaling and accidentally wrote a 900-word apology to myself', 'Turns out I''m nice. Who knew? Highly recommend. Put stickers on it. Brain likes stickers.', 5),
  ('Portland coffee shop had a ''seasonal sadness latte'' and I felt seen', 'It''s just espresso with a tiny sun in it. Or maybe orange zest. Hard to say through the tears.', 12),
  ('San Francisco hill tried to yeet me into the bay', 'Respect to all cyclists here. Your calves are forged by gods and also cyclists.', 7),
  ('I stared at a bug for five minutes and we both learned patience', 'He was a little guy with big dreams. I named him Jace. He left. Classic.', 16),
  ('UI STRESS TEST TITLE: Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace Jace', 'If this wraps ugly, it''s a feature. Don''t @ me.', 10),
  ('LA traffic turned my podcast into an audiobook into a lifestyle', 'I finished a 12-episode series and started a language course. I now know 7 words of Icelandic and 4 new ways to swear at brake lights.', 16),
  ('We need a Jacebook feature that translates cat meows', 'I truly believe Mr. Whiskers called me ''bro'' today. He also asked for rent.', 24),
  ('Devs, be honest: how many console.logs are in production', 'I can stop anytime. I won''t, but I can. They''re like tiny hugs from the server.', 1),
  ('Accidentally napped with a tortilla on my chest', 'I was making a quesadilla. I failed. But also I succeeded because the nap was elite.', 19),
  ('Atlanta thunder made my dog turn into a scarf', 'Wrapped around my neck like an anxious, fluffy fashion statement. We survived together.', 19),
  ('Philly pretzel discourse', 'Mustard or cheese? There is a right answer but I''m diplomatic. Also, someone please twist my email inbox into a pretzel and throw it away.', 27),
  ('Las Vegas Jace recommendation: karaoke at 3 pm on a Tuesday', 'No lines, no shame, maximum echo. You''re welcome.', 28),
  ('I saw a raccoon with a slice of pizza like he paid rent there', 'Sir was strutting down the alley at 2 am with swagger. I respected the hustle.', 9),
  ('Trying to be mysterious but I keep oversharing', 'Hello I am Jace and my personality is ''here are my thoughts'' followed by 9 paragraphs.', 23),
  ('San Diego beach day: sunscreen applied like a Jackson Pollock', 'I have stripes. I am modern art. Someone hang me in a gallery with a fan.', 29),
  ('Portland rain tried to baptize me into a new person', 'I declined. Still soggy. Coffee helped.', 12),
  ('I told myself no more candles and then bought a candle called ''Forest Spreadsheet''', 'Smells like pine and anxiety. 10/10.', 13),
  ('I asked my plant how she''s doing and she replied ''photosynthesizing, babe''', 'I''m projecting obviously. But she''s thriving and I''m proud.', 15),
  ('Detroit parking meter took my quarters and my trust', 'It blinked ''ERROR'' and I blinked tears. City said that''s the fee.', 24),
  ('UI edge case: empty title and long message incoming', 'This is a deliberately long message to test the UI wrapping, clamping, and overall resilience. If you are reading this, please know that I, Jace, wrote it while eating cereal directly from the box and contemplating whether my houseplant is judging my font choices. The message continues because we need length: waffles, raccoons, spreadsheets, cardio, existentialism, and that weird smell in the office fridge. Okay bye.', 10),
  ('Boston clam chowder vs. the soul', 'One is creamy and comforting. The other is my inbox. Guess which one I''m enjoying.', 13),
  ('Lasagna is just fancy pasta cake and I will not elaborate', 'Except I will. Layers. Frosting (cheese). Structure. Celebration. Happy birthday to my dinner.', 4),
  ('Today''s productivity fueled entirely by petty spite', 'Someone said I couldn''t finish this, so I became a machine built from caffeine and star charts.', 6),
  ('UI stress: super short', 'k', 18),
  ('UI stress: super long message max test', 'This message is intentionally very, very long to test the upper bound near one thousand characters. Jace typing like a novelist at a coffee shop with a scarf that is objectively too long for the temperature. Let''s list things: coffee (always), code (sometimes functional), cats (often judgmental), cardio (allegedly), candles (financially irresponsible), calamari (yum), cartwheels (rare), curiosity (constant). If this wraps cleanly, our CSS is doing great. If not, I apologize to future Jace who has to fix it while muttering ''why did I do this'' under his breath. Also inserting filler because we want length without nonsense symbols: waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle waffle. End of essay. Kind of.', 10),
  ('Grocery self-checkout called me a thief again', 'I bagged bananas. It said ''unexpected item''. The item was truth and my fury.', 22),
  ('I tried to fix a squeaky cabinet and invented jazz instead', 'Every time it opens it does a little squeal on the two. Honestly? Kind of a vibe.', 11),
  ('I spent $14 on toast and felt emotions', 'It had microgreens. It had an origin story. It had my rent.', 7),
  ('Salt Lake City sky looked like a screensaver and I clapped', 'Couldn''t help it. Clouds did a performance and I was the audience of one.', 26),
  ('Am I a runner now or did I just buy shorts', 'I will update after one jog and six naps.', 23),
  ('UI note: this title contains punctuation, CAPS, and way too many commas, commas, commas, but remains under the limit like a responsible little headline', 'If you break, title, I''ll cry (respectfully).', 9),
  ('Miami humidity turned my hair into a personality', 'I am 70% water and 30% frizz. Call me cumulonimbus.', 20),
  ('Columbus Jace''s nap schedule (pro): yes', 'Cons: everything else. Pro: napped.', 18),
  ('I found a notebook from 2017 and wow, that Jace was optimistic', 'He believed in schedules and kale. I respect him. I am not him.', 27),
  ('San Diego sea lions gossip louder than I do', 'They were absolutely talking about me. I could feel it.', 29),
  ('I made a to-do list and then immediately did something not on it', 'Then I wrote it on the list just to cross it off. Self-care.', 3),
  ('Pizza place had a vibe so strong I forgave the sticky table', 'They yelled my name (Jace), gave me a slice the size of a pillow, and told me to live my truth. I did.', 2),
  ('Dallas thrift store bargain of the century', 'Found a denim jacket that makes me look like I produce indie bands. It was $6. I am unstoppable.', 14),
  ('New York crosswalk gave me half a second and a challenge', 'I accepted. I parkoured. I survived.', 10),
  ('I tried to learn harmonica for 12 minutes', 'I think my neighbors filed a maritime complaint. I do sound like a boat.', 5),
  ('I put my phone down and my brain started buffering', 'Spinning wheel. Spinning wheel. And we''re back.', 22),
  ('Jace confession: I''m afraid of my own inbox', 'It''s growing. It''s learning. It has subfolders now. Send reinforcements.', 24),
  ('Atlanta Jace''s peach review thread (peaches are elite)', 'Sweet, messy, perfect. Like me after two tacos.', 19),
  ('I told my friend I''d be there in five. I arrived tomorrow.', 'Time is fake. Friendship is real. I brought snacks so it''s fine.', 6),
  ('I tried to wink and accidentally blinked aggressively', 'The moment passed. The vibe shattered. We move.', 28),
  ('I burned my tongue on soup and immediately repeated the mistake', 'Fool me once: soup. Fool me twice: still soup. Fool me thrice: legally soup''s fault.', 11),
  ('Detroit coney dog diplomacy', 'Two spots, one stomach. I will report back with ketchup-based data.', 24),
  ('UI tiny: period.', '.', 4),
  ('UI empty message stress test', '', 9),
  ('UI near-max title: A very, very, very long but still under two hundred fifty characters title where Jace tries to push the boundaries of headline length to see if the layout explodes or gracefully wraps like a polite burrito in CSS', 'If this looks good, send a high five through the screen.', 13),
  ('I am once again asking for pasta recommendations', 'Not fancy. Cozy. Like a hug from a nonna who calls me ''Jaccé'' for some reason.', 3),
  ('Salt Lake City snow hit and my car said ''nope''', 'We, the people of the driveway, declare today a blanket and tea day.', 26),
  ('I reorganized my desk and found three scissors', 'Why. How. Also where did my single functioning pen go.', 21),
  ('I waved at someone who was waving at the person behind me', 'I am now moving states.', 17),
  ('Remote meeting where I spoke while on mute for a full paragraph', 'Everyone watched my little square go silent opera. Then the chat said ''you''re muted''. Tragic. Poetic.', 7),
  ('UI mid-length title for balance', 'This is a medium message for Goldilocks-level UI testing. Not too short, not too long, just right, sprinkled with a few commas, and a gentle vibe so your eyes get a rest between the spicy long ones.', 18),
  ('Portland thrift haul: cardigan that screams ''professor of vibes''', 'Ten dollars. Ten out of ten. Tenure incoming.', 12),
  ('I tried pickleball and discovered I am exactly average', 'Which is honestly perfect. I wore fun socks and called it a win.', 27),
  ('My plant did a new leaf and I cried', 'We''re both growing. Hers is shinier.', 15),
  ('UI MAX MESSAGE TEST (near 1000 chars) – Dear future Jace, if this renders weird, forgive me', 'This extremely long message exists purely to exercise your UI. It should approach the limit without crossing it, filled with normal words, no trick punctuation, and plenty of wholesome Jace energy. Imagine a wall of text that still feels readable: short sentences. Occasional jokes. Breathing room. We talk about pizza (square is supreme), productivity (elastic concept), pets (perfect), and posture (help). We mention that sometimes a sentence goes on for a bit to simulate real rambling because people do that and it''s fine and even a little charming when done sparingly, especially if broken up later so the reader doesn''t get annoyed by a single unstoppable river of letters. If this wraps without jank and truncates where appropriate, give yourself a snack. You''ve earned it. High five from past Jace.', 10),
  ('San Francisco fog tried to steal my hat and my mood', 'I let it have the mood. Kept the hat. Growth.', 7),
  ('I made soup that tasted like ''liquid beige'' and corrected it with reckless lemon', 'Citrus: the reset button. Jace: the button presser.', 29),
  ('UI tiny again', 'ok', 22),
  ('I touched grass. It was fine.', 'I rate it 7/10. Might try again next week.', 25),
  ('Salt Lake thrift store had a bowl that looked haunted, I purchased', 'If my cereal starts whispering I will simply ignore it. Boundaries.', 26),
  ('I saw my reflection in a storefront and decided to become a hat guy', 'Day 1: hat acquired. Day 2: confidence pending.', 23);

INSERT INTO comments (message, post_id, user_id)
VALUES
  ('Same, Jace. Mood.', 1, 2),
  ('Peak Jace energy.', 1, 3),
  ('.', 1, 4),
  ('Same, Jace. Mood.', 2, 3),
  ('Screenshotted for science.', 2, 4),
  ('.', 2, 5),
  ('Same, Jace. Mood.', 3, 4),
  ('The accuracy hurts.', 3, 5),
  ('Bookmarked for future-me who will forget why this was funny and then laugh again. The cadence, the tiny sprinkle of chaos, the tastefully unhinged delivery—it all sings. Consider me nourished by vibes and a reasonably responsible quantity of caffeine. If this wraps cleanly and the UI remains calm, please award an imaginary gold star to the layout team and one bonus snack to Jace.', 3, 6),
  ('Same, Jace. Mood.', 4, 5),
  ('Sending supportive carbs.', 4, 6),
  ('I read this, nodded like a wise raccoon, and decided that productivity is mostly about timing and snacks. The details here are so good I could annotate them like a poetry class. Anyway, thanks for the serotonin burst and the excuse to procrastinate in style. May your next tab be the right one and your coffee be the perfect degree of dramatic.', 4, 7),
  ('Same, Jace. Mood.', 5, 6),
  ('Strong agree.', 5, 7),
  ('This is the exact brand of mild chaos I subscribe to: humane, funny, slightly self-roasty, and just specific enough to feel real. If the UI survives this comment without weird hyphenation or layout tantrums, that''s a W for the whole squad. Carry on, Jace. The vibes are immaculate, the commas are tasteful, and I''m clapping internally like a well-behaved seal.', 5, 8),
  ('Same, Jace. Mood.', 6, 7),
  ('Elite take. No notes.', 6, 8),
  ('Adding a long-ish comment to poke the edges: lines, wrapping, clamping, the whole parade. No cursed characters, just friendly words marching in formation. If you can read this without scrolling a mile, congratulations to the CSS on being both chic and functional. Also, pizza with squares forever; corners are destiny.', 6, 9),
  ('Same, Jace. Mood.', 7, 8),
  ('Snort-laughed at this.', 7, 9),
  ('ok', 7, 10),
  ('Same, Jace. Mood.', 8, 9),
  ('Respectfully screaming.', 8, 10),
  ('Screenshotted and sent to the group chat titled "we are trying our best." The energy here feels like a power-walk through a grocery store with a chaotic list and perfect aisle timing. Should be just under five hundred characters, breezy enough for mobile, strong enough for desktop. UI, take a bow; devs, accept a polite golf clap.', 8, 11),
  ('Same, Jace. Mood.', 9, 10),
  ('Saving this to Jacebook.', 9, 11),
  ('As a known enjoyer of little internet essays, I would like to subscribe to this channel of tiny honesty. Please keep the jokes, the gentle self-dunks, and the oddly specific details about snacks. If this comment wraps beautifully, we celebrate. If it doesn''t, we file a tasteful bug and fix it before lunch like legends.', 9, 12),
  ('Same, Jace. Mood.', 10, 11),
  ('Following for updates.', 10, 12),
  ('whew.', 10, 13),
  ('Same, Jace. Mood.', 11, 12),
  ('Peak Jace energy.', 11, 13),
  ('Consider this my formal endorsement and also an informal snack break. The tone? Chef''s kiss. The timing? Impeccable. The subtext? Probably carbs. Anyway, I''m rooting for this entire thread to be archived in a museum of righteous internet posts.', 11, 14),
  ('Same, Jace. Mood.', 12, 13),
  ('Screenshotted for science.', 12, 14),
  ('I can feel the precise ratio of humor to sincerity and it is premium. If this platform had a "save to mood board" button I would have mashed it already. Kudos to the punctuation for working overtime without showing it.', 12, 15),
  ('Same, Jace. Mood.', 13, 14),
  ('The accuracy hurts.', 13, 15),
  ('This belongs in a group chat and possibly a syllabus. It''s giving self-awareness with a side of bread. I respect the craft, the courage, and the commitment to bit. May your notifications be kind and your CSS behave.', 13, 16),
  ('Same, Jace. Mood.', 14, 15),
  ('Sending supportive carbs.', 14, 16),
  ('Printing this out and taping it to the side of my monitor like a gremlin who collects vibes for winter. Ten out of ten, would reread on a Monday.', 14, 17),
  ('Same, Jace. Mood.', 15, 16),
  ('Strong agree.', 15, 17),
  ('Standing ovation but quietly because I''m in a coffee shop. Strong work, team Jace. May your tabs close themselves and your pizza be square.', 15, 18),
  ('Same, Jace. Mood.', 16, 17),
  ('Elite take. No notes.', 16, 18),
  ('I promise I''m nodding respectfully at my screen right now. The restraint? The pacing? The micro-chaos? Gorgeous. Flawless. Add to cart.', 16, 19),
  ('Same, Jace. Mood.', 17, 18),
  ('Snort-laughed at this.', 17, 19),
  ('.', 17, 20),
  ('Same, Jace. Mood.', 18, 19),
  ('Respectfully screaming.', 18, 20),
  ('lol', 18, 21),
  ('Same, Jace. Mood.', 19, 20),
  ('Saving this to Jacebook.', 19, 21),
  ('Filed under: too relatable.', 1, 2),
  ('Same, Jace. Mood.', 20, 21),
  ('Following for updates.', 20, 22),
  ('Chaos, but make it cozy.', 2, 3),
  ('Same, Jace. Mood.', 21, 22),
  ('Peak Jace energy.', 21, 23),
  ('Relatable in 4K.', 3, 4),
  ('Same, Jace. Mood.', 22, 23),
  ('Screenshotted for science.', 22, 24),
  ('This lives in my head rent-free now.', 4, 5),
  ('Same, Jace. Mood.', 23, 24),
  ('I feel violently seen (in a good way).', 5, 6),
  ('Adding to the Jacebook lore.', 6, 7),
  ('Screaming internally (politely).', 7, 8),
  ('This is my Roman Empire.', 8, 9),
  ('I inhaled this post.', 9, 10),
  ('Bookmarking for future chaos.', 10, 11),
  ('Certified banger.', 11, 12),
  ('This unlocked new dialogue options.', 12, 13),
  ('I will be thinking about this later.', 13, 14),
  ('We are so back.', 14, 15),
  ('This is art, actually.', 15, 16),
  ('Approved by the Committee of One.', 16, 17),
  ('Desk laugh achieved.', 17, 18),
  ('Relatable like a comfy hoodie.', 18, 19),
  ('Spicy truth nugget.', 19, 20),
  ('Palate cleanser for the feed.', 20, 21),
  ('Statement stands.', 21, 22),
  ('This post sees into my soul and orders a snack.', 22, 23),
  ('Cannot. Will not. Love it.', 23, 24),
  ('This is character development.', 24, 25),
  ('Gasp in Helvetica.', 25, 26),
  ('Chef-approved chaos.', 26, 27),
  ('Low stakes, high vibes. Perfect.', 27, 28),
  ('This is legally funny in 48 states.', 28, 29),
  ('I respect this post''s hustle.', 29, 1),
  ('Felt like a tiny movie.', 30, 2),
  ('Energy: immaculate.', 31, 3),
  ('Adding to my mood board.', 32, 4),
  ('Correct and good.', 33, 5),
  ('Pinning this to my brain corkboard.', 34, 6),
  ('I whisper-laughed and scared my coffee.', 35, 7),
  ('This has main-character breakfast energy.', 36, 8),
  ('10/10 would read again.', 37, 9),
  ('Vibes: curated. Jokes: artisanal.', 38, 10),
  ('Putting this on a sticky note.', 39, 11),
  ('This is community theater at its best.', 40, 12),
  ('The internet at its finest medium-rare.', 41, 13),
  ('Laughed in lowercase.', 42, 14),
  ('A tiny masterpiece.', 43, 15),
  ('Emotion: noted. Snack: obtained.', 44, 16),
  ('Chaos density: perfect.', 45, 17),
  ('I''m framing this on my fridge.', 46, 18),
  ('We did, in fact, need this.', 47, 19),
  ('Adding this to the lore bible.', 48, 20),
  ('This will fuel me for three meetings.', 49, 21),
  ('My serotonin said thank you.', 50, 22),
  ('Elegantly unhinged.', 51, 23),
  ('Approved by the vibe council.', 52, 24),
  ('I will be quoting this at brunch.', 53, 25),
  ('My inner raccoon is applauding.', 54, 26),
  ('Spoke to me and also to my snacks.', 55, 27),
  ('This post has corner-piece pizza energy.', 56, 28),
  ('This healed one (1) brain cell.', 57, 29),
  ('Tiny riot of joy.', 58, 1),
  ('Genuinely delightful.', 59, 2),
  ('Pinned under: things I needed today.', 60, 3),
  ('Quietly iconic.', 61, 4),
  ('This is peak mild chaos.', 62, 5),
  ('Inspiring a responsible amount of mischief.', 63, 6),
  ('My attention span said “yup.”', 64, 7),
  ('Approved: brain, heart, and snack drawer.', 65, 8),
  ('Cinema. Truly.', 66, 9),
  ('I feel called in, not out.', 67, 10),
  ('This post bought a tiny condo in my mind.', 68, 11),
  ('Adding to the scrapbook of tiny wins.', 69, 12),
  ('I did a respectful nod IRL.', 70, 13),
  ('I will be referencing this for weeks.', 71, 14),
  ('This is responsible interneting.', 72, 15),
  ('The exact flavor of chaos I ordered.', 73, 16),
  ('I''m printing this on a mug.', 74, 17),
  ('Feed cleanser achieved.', 75, 18),
  ('We ride at dawn (after coffee).', 76, 19),
  ('I aspire to this tone daily.', 77, 20),
  ('Vibe check: passed.', 78, 21),
  ('The good kind of unhinged.', 79, 22),
  ('I''m saving this to my brain''s Downloads folder.', 80, 23),
  ('This gave my inbox hope.', 81, 24),
  ('Feral but formatted.', 82, 25),
  ('Conducting a small, polite applause.', 83, 26),
  ('Snack-forward commentary. Love to see it.', 84, 27),
  ('Absolutely unproblematic and delicious.', 85, 28),
  ('Pinned to the corkboard of my heart.', 86, 29),
  ('Gently iconic.', 87, 1),
  ('Laughed in sans-serif.', 88, 2),
  ('This is peak “we''re all trying.”', 89, 3),
  ('Approved by three brain cells and a raccoon.', 90, 4),
  ('Crying in lowercase.', 91, 5),
  ('Gave this a chef''s nod.', 92, 6),
  ('This is a tiny parade of joy.', 93, 7),
  ('Elevated comfort internet.', 94, 8),
  ('I have adopted this sentence.', 95, 9),
  ('Too relatable; sending carbs.', 96, 10),
  ('Emotionally relevant data detected.', 97, 11),
  ('Mood registered and filed with the proper authorities.', 100, 14),
  ('.', 54, 28),
  ('Same, Jace. Mood.', 55, 27),
  ('Strong agree.', 55, 28),
  ('👏', 55, 29),
  ('Same, Jace. Mood.', 56, 28),
  ('Elite take. No notes.', 56, 29),
  ('I almost did a tiny clap at my desk. Almost.', 56, 1),
  ('Same, Jace. Mood.', 57, 29),
  ('Snort-laughed at this.', 57, 1),
  ('Leaving one thoughtful sentence to keep the dataset spicy but civilized.', 57, 2),
  ('Same, Jace. Mood.', 58, 1),
  ('Respectfully screaming.', 58, 2),
  ('.', 58, 3),
  ('Same, Jace. Mood.', 59, 2),
  ('Saving this to Jacebook.', 59, 3),
  ('lol', 59, 4),
  ('Same, Jace. Mood.', 60, 3),
  ('Following for updates.', 60, 4),
  ('respectfully yes.', 60, 5),
  ('Same, Jace. Mood.', 61, 4),
  ('Peak Jace energy.', 61, 5),
  ('.', 61, 6),
  ('Same, Jace. Mood.', 62, 5),
  ('Screenshotted for science.', 62, 6),
  ('lol', 62, 7),
  ('Same, Jace. Mood.', 63, 6),
  ('The accuracy hurts.', 63, 7),
  ('ok', 63, 8),
  ('Same, Jace. Mood.', 64, 7),
  ('Sending supportive carbs.', 64, 8),
  ('Monitoring wrap, rhythm, and readability. Passing with style.', 64, 9),
  ('Same, Jace. Mood.', 65, 8),
  ('Strong agree.', 65, 9),
  ('👏', 65, 10),
  ('Same, Jace. Mood.', 66, 9),
  ('Elite take. No notes.', 66, 10),
  ('lol', 66, 11),
  ('Same, Jace. Mood.', 67, 10),
  ('Snort-laughed at this.', 67, 11),
  ('.', 67, 12),
  ('Same, Jace. Mood.', 68, 11),
  ('Respectfully screaming.', 68, 12),
  ('The vibes are immaculate and the line-length is humane. Chef-approved.', 68, 13),
  ('Same, Jace. Mood.', 69, 12),
  ('Saving this to Jacebook.', 69, 13),
  ('lol', 69, 14),
  ('Same, Jace. Mood.', 70, 13),
  ('Following for updates.', 70, 14),
  ('unreasonably funny.', 70, 15),
  ('Same, Jace. Mood.', 71, 14),
  ('Peak Jace energy.', 71, 15),
  ('.', 71, 16),
  ('Same, Jace. Mood.', 72, 15),
  ('Screenshotted for science.', 72, 16),
  ('lol', 72, 17),
  ('Same, Jace. Mood.', 73, 16),
  ('The accuracy hurts.', 73, 17),
  ('This is your friendly neighborhood long-ish comment making sure nothing explodes in mobile view. Everyone remain calm and hydrated.', 73, 18),
  ('Same, Jace. Mood.', 74, 17),
  ('Sending supportive carbs.', 74, 18),
  ('.', 74, 19),
  ('Same, Jace. Mood.', 75, 18),
  ('Strong agree.', 75, 19),
  ('👏', 75, 20),
  ('Same, Jace. Mood.', 76, 19),
  ('Elite take. No notes.', 76, 20),
  ('lol', 76, 21),
  ('Same, Jace. Mood.', 77, 20),
  ('Snort-laughed at this.', 77, 21),
  ('I see your chaos and raise you a responsible bedtime. Still laughing tho.', 77, 22),
  ('Same, Jace. Mood.', 78, 21),
  ('Respectfully screaming.', 78, 22),
  ('.', 78, 23),
  ('Same, Jace. Mood.', 79, 22),
  ('Saving this to Jacebook.', 79, 23),
  ('lol', 79, 24),
  ('Same, Jace. Mood.', 80, 23),
  ('Following for updates.', 80, 24),
  ('bless this post.', 80, 25),
  ('Same, Jace. Mood.', 81, 24),
  ('Peak Jace energy.', 81, 25),
  ('.', 81, 26),
  ('Same, Jace. Mood.', 82, 25),
  ('Screenshotted for science.', 82, 26),
  ('lol', 82, 27),
  ('Same, Jace. Mood.', 83, 26),
  ('The accuracy hurts.', 83, 27),
  ('ok', 83, 28),
  ('Same, Jace. Mood.', 84, 27),
  ('Sending supportive carbs.', 84, 28),
  ('UI audit: legible, lovable, line-broken with grace. Approved.', 84, 29),
  ('Same, Jace. Mood.', 85, 28),
  ('Strong agree.', 85, 29),
  ('👏', 85, 1),
  ('Same, Jace. Mood.', 86, 29),
  ('Elite take. No notes.', 86, 1),
  ('I will be thinking about this while pretending to focus on something else.', 86, 2),
  ('Same, Jace. Mood.', 87, 1),
  ('Snort-laughed at this.', 87, 2),
  ('.', 87, 3),
  ('Same, Jace. Mood.', 88, 2),
  ('Respectfully screaming.', 88, 3),
  ('Dropped by to say this is exactly the level of specificity that makes the internet bearable.', 88, 4),
  ('Same, Jace. Mood.', 89, 3),
  ('Saving this to Jacebook.', 89, 4),
  ('lol', 89, 5),
  ('Same, Jace. Mood.', 90, 4),
  ('Following for updates.', 90, 5),
  ('sending snacks.', 90, 6),
  ('Same, Jace. Mood.', 91, 5),
  ('Peak Jace energy.', 91, 6),
  ('ok', 91, 7),
  ('Same, Jace. Mood.', 92, 6),
  ('Screenshotted for science.', 92, 7),
  ('lol', 92, 8),
  ('Same, Jace. Mood.', 93, 7),
  ('The accuracy hurts.', 93, 8),
  ('This single post is carrying my attention span on its back like a tiny champion.', 93, 9),
  ('Same, Jace. Mood.', 94, 8),
  ('Sending supportive carbs.', 94, 9),
  ('Just long enough to be funny, short enough to be polite. Perfect.', 94, 10),
  ('Same, Jace. Mood.', 95, 9),
  ('Strong agree.', 95, 10),
  ('👏', 95, 11),
  ('Same, Jace. Mood.', 96, 10),
  ('Elite take. No notes.', 96, 11),
  ('lol', 96, 12),
  ('Same, Jace. Mood.', 97, 11),
  ('Snort-laughed at this.', 97, 12),
  ('Adding one last long-ish line near the end to check any off-by-one layout gremlins. If you can read this, the CSS exorcism worked. Carry on.', 97, 13),
  ('Valid. I feel this.', 98, 12),
  ('Respectfully screaming.', 98, 13),
  ('ok', 98, 14),
  ('Too real, sending vibes.', 99, 13),
  ('Saving this to Jacebook.', 99, 14),
  ('lol', 99, 15),
  ('Mood registered and filed.', 100, 14),
  ('Following for updates.', 100, 15),
  ('noted.', 100, 16);
`;

async function clear(connStr) {
  console.log('clearing...');
  const client = new Client({
    connectionString: connStr,
  });
  await client.connect();
  await client.query(clearSQL);
  await client.end();
  console.log('done');
}

async function populate(connStr) {
  console.log('seeding...');
  const client = new Client({
    connectionString: connStr,
  });
  await client.connect();
  await client.query(populateSQL);
  await client.end();
  console.log('done');
}

module.exports = {
  clear,
  populate,
};
